//Chnage color og background for each fact
var colorIndex = 0;
function changeColor() {
    var col = document.getElementById("section");
    if( colorIndex >= colors.length ) {
        colorIndex = 0;
    }
    col.style.backgroundColor = colors[colorIndex];
    colorIndex++;
}

//Get random Fact from randomFacts array
function getRandom(){
	 var random = randomFacts[Math.floor(Math.random() * randomFacts.length)];
   document.getElementById("message").innerHTML=random;
}

//Serve Random Fact to page
var btnNext = document.getElementById("btnNext");
btnNext.onclick = function(){
	getRandom();
	changeColor();
};


//Serve Random Fact to page
window.onkeydown = function(event) {
  if (event.keyCode == 13) {
    getRandom();
	changeColor();
  }
};

//Various Background Colors
var colors = [ "blue", "teal", "green", "orange", "black", "seagreen", "purple", "darksalmon", "magenta", "chocolate", "darkred", "darkviolet", "darkslateblue", "dodgerBlue",
			  "darkblue", "forestgreen", "deepskyblue", "midnightblue", "red", "steelblue", "maroon", "mediumorchid", "darkggoldenrod", "peru", "rosybrown", "sandybrown", "sienna",
			  "olive", "darkgreen",   "lightseagreen", "tomato", "limegreen", "mediumseagreen", "olivedrab", 
			  "gray", "dimgray", "slategray", "darkorange", "mediumvioletred", "blueviolet", "indigo",  
			  "rebeccapurple", "crimson", "darkolivegreen", "fireBrick", 
				 ];

//Random Facts
var randomFacts = [
				"When Skee-Ball was first invented, the lane was 36 feet long. Not many people could roll the ball that far, so they shortened it to 14 feet.",
				"A newborn giant panda is about the size of a stick of butter. ",
				"Whales still have hip bones. ",
				"The country with the most feral camels is Australia.",
				"Nearly 30% of Dalmatian dogs are born with complete or partial hearing loss.",
				"Cashews are related to poison ivy. ",
				"Cashews are actually a fleshy fruit.",
				"PETA once asked the Pet Shop Boys to consider changing their name to Rescue Shelter Boys.",
				"Crickets' ears are located on their front legs, a little below their knees.",
				"Despite its name, Equatorial Guinea doesn't lie on the Equator, but just north of it.",
				"An earthquake on December 16th, 1811, caused parts of the Mississippi River to flow backwards.",
				"Peladophobia is the fear of bald people.",
				"The national animal of Scotland is the unicorn.",
				"The number 4 is the only number with the same number of letters as the meaning of its name.",
				"Why is bubble gum pink? When it was invented, pink was the only food dye on hand.",
				"Lead will float in mercury, but a lump of tungsten will sink right to the bottom.",
				"Twitter's bird logo is named Larry, for Larry Bird. ",
				"Food chemist William A. Mitchell helped invent Tang, Cool Whip, and Pop Rocks.",
				'The flashes of colored light you see when you rub your eyes are called "phosphenes." ',
				"Banging your head against a wall burns 150 calories an hour.",
				"An eagle can kill a young deer and fly away with it.",
				"A toaster uses almost half as much energy as a full-sized oven.",
				"Australia has over 10,000 beaches. You could visit a new beach everyday for over 27 years!",
				"Viagra, when dissolved in water, can make cut-flowers stay erect for up to a week longer than they usually would. Try it!",
				"Catnip is ten-times more effective at repelling mosquitoes than DEET, the main substance used in insect repellents.",
				"The directors of the film Despicable Me actually wrote their own language for the Minions called Minionise.",
				"If eaten in one meal, 30 to 90 grams of polar bear liver is enough to kill a human being.",
				"Hares are born with fur and can see whilst rabbits are born ‘naked’ and blind.",
				"Approximately 1,000,000 dogs in the U.S. are named as the heirs of their owners’ wills.",
				"In 1984, Pac-Man introduced the first side scrolling game in the series, which is the game everyone knows today.",
				"An average person’s yearly fast food intake will contain 12 pubic hairs. ",
				"In the wild, pineapple plants can live & fruit for up to 50 years.",
				"Sonic the Hedgehog has registered itself in Guinness Book of World Records for being the fastest gaming character ever.",
				"The least financially successful Harry Potter film made approximately $90 million more than the most successful Twilight movie.",
				"You are three times more likely to get a virus on your computer from a Religious website than from a Porn website.",
				"The very first Apple logo featured Sir Isaac Newton sitting underneath a tree, with an apple about to hit his head.",
				"A UFO is reported once every three minutes in the world.",
				"On an average work day, a typist’s fingers travel about 12.6 miles.",
				"Alaska is the only state in America that can be typed on one row of a traditional English QWERTY keyboard.",
				"86% of people try to plug their USB devices upside down.",
				"Email has been around longer the world-wide web!",
				"The very first domain name registered was www.symbolics.com, on the 15th March, 1985.",
				"Anthony Greco was the first man ever arrested for sending spam messages in 2005.",
				"All the letter combinations from aaa.com to zzz.com have already been registered.",
				"Amazon now sells more eBooks than it does printed books!",
				"The original URL for Yahoo was http://akebono.stanford.edu",
				"The last game for the Sega Mega Drive was released in 2010 and was so popular it sold out before release.",
				"Surgeons who grew up playing video games make 37% fewer mistakes.",
				"The Sega Dreamcast was the first 128-bit console in the market.",
				"Phantom Vibration Syndrome is the name given when someone thinks their phone is vibrating but isn’t.",
				"Today, the number of text messages sent and received everyday, is more than the total population of the planet.",
				"There are Braille accessories for smart phones.",
				"Facebook has a blue colour scheme because the creator, Mark Zuckerberg cannot see the colours red & green.",
				"Someone on Twitter who has a million or more followers is known as a “Twillionaire”.",
				"60% of LinkedIn members have clicked one of their adverts.",
				"Remember MySpace? Well it has over 200 million registered users.",
				"A survey showed 29 per cent of adults say they have been splashed or scalded by hot drinks while dunking biscuits.",
				"Ortharexia Nervosa is an eating disorder where the sufferer is obsessed with eating healthy food.",
				"Ketchup was sold in the 1830s as medicine.",
				"Dry swallowing one teaspoon of sugar can commonly cure hic-ups.",
				"In Kentucky, it is illegal to carry an ice cream cone in your back pocket.",
				"The fear of cooking is known as Mageirocophobia and is a recognised phobia.",
				"The tea bag was introduced in 1908 by Thomas Sullivan of New York.",
				"The tall chef’s hat is called a toque.",
				"Arachibutyrophobia is the fear of peanut butter sticking to the roof of the mouth.",
				"In South Africa, termites and ants are often roasted and eaten by the handful, like popcorn.",
				"Every time you lick a stamp, you consume 1/10 of a calorie.",
				"Pearls melt in vinegar.",
				"The ’57’ on the Heinz ketchup bottle represents the number of pickle types the company once had.",
				"Marmite was first introduced into the UK in 1902.",
				"The ancient Greeks chewed a gum-like substance called mastic that came from the bark of a tree.",
				"Honeybee workers must visit 2 million flowers to make one pound of honey.",
				"The fear of vegetables is called Lachanophobia.",
				"Almonds are a member of the peach family.",
				"If you boil beetroot in water, and then massage the water into your scalp each night, it works as an effective cure for dandruff.",
				"In the United States, lettuce is the second most popular fresh vegetable.",
				"Grape growing is the largest food industry in the world as there are more than 60 species and 8000 varieties of grapes.",
				"The average person eats eight pounds of grapes each year.",
				"There are more than 7,000 varieties of apples grown in the world.",
				"A cluster of bananas id formerly called a ‘hand’. Along that theme, a single banana is called a ‘finger’.",
				"Onion is Latin for ‘large pearl’.",
				"Apples, pears, cherries and strawberries are all members of the rose family.",
				"The word vegetable has no scientific definition, so it’s still acceptable to call a tomato a vegetable.",
				"In the Philippines, it is considered good luck if a coconut is cleanly split open without jagged edges.",
				"When cranberries are ripe, they bounce like a rubber ball.",
				"The most amount of grapes eaten in 3 minutes is 133. This record was set in 2001 by Mat Hand, from the UK.",
				"There are more than 10,000 varieties of tomatoes.",
				"In 2001, there were more than 300 banana-related accidents in Britain, most involving people slipping on skins.",
				"Carrots have zero fat content.",
				"Peanuts can be used to make dynamite.",
				"A watermelon is over 92% water by weight.",
				"Alliumphobia is the fear of garlic.",
				"A row of corn always has an even number.",
				"The pumpkin originated in Mexico about 9,000 years ago.",
				"Square watermelons sell for about $85.",
				"Turnips are high in fibre, Vitamin C, Calcium and Potassium.",
				"Eating a lot of beetroot turns your pee into a pink colour.",
				"Biting a wooden spoon whilst chopping an onion will stop your eyes from watering.",
				"Each pineapple plant only produces just one pineapple per year.",
				"Lettuce is a member of the sunflower family.",
				"Blueberries are a good source of Vitamin C and fibre.",
				"Pumpkin flowers are edible.",
				"Peaches are the third most popular fruit grown in America.",
				"We are eating 900% more broccoli than we did 20 years ago.",
				"The Whirlpool Galaxy (M51) was the very first celestial object to be identified as being spiral.",
				"A light year is the distance covered by light in a single year, this is equivalent to 6 billion miles!",
				"The width of the Milky Way is around 100,000 light years.",
				"The Sun is over 300,000 times larger than Earth.",
				"Footprints and tyre tracks left by astronauts on the moon will stay there forever as there is no wind to blow them away.",
				"Because of lower gravity, a person who weighs 100kg on earth would only weigh 38kg on the surface of Mars.",
				"64 moons orbit Jupiter.",
				"The Martian day is 24 hours 39 minutes and 35 seconds.",
				"The Sun makes a full rotation once every 25-35 days.",
				"Venus is the only planet that spins backwards relative to the other planets.",
				"The force of gravity can sometimes cause comets to tear apart.",
				"It is thanks to the Sun and our own moons gravity that we have high and low tides.",
				"Our moon is moving away from Earth at a rate of 4cm (1.6 Inches) per year! (Read More)",
				"According to mathematics, white holes are possible, although as of yet, we have found none.",
				"Our moon is around 4.5 billion years old.",
				"There are more volcanoes on Venus than any other planet within our solar system.",
				"Uranus’ blue glow is down to the methane in its atmosphere, which filters out all the red light.",
				"The four planets in our solar system that are known as gas giants are Jupiter, Neptune, Saturn and Uranus.",
				"Uranus has 27 moons that have been discovered so far.",
				"Because of its unique tilt, a single night on Uranus lasts for 21 years!",
				"Triton, one of Neptune’s moons, is gradually getting closer to the planet it orbits.",
				"The only large moon in our solar system to orbit in the opposite direction of its planet is Neptune’s moon, Triton.",
				"Neptune takes 165 years to make one orbit of the moon. this means that since it’s discovery in 1846, it has only completed just one orbit!",
				"Charton is one of the moons of Pluto, and is only slightly smaller than Pluto itself.",
				"The Space Station is the largest manned object ever sent into space.",
				"'Moon' was Buzz Aldrin’s mother’s maiden name.",
				"The first woman in space was a Russian called Valentina Tereshkova.",
				"There are currently 166 moons in our solar system.",
				"The largest star known to man is R136a1, which has a mass of 265-320 times that of our sun!",
				"The first artificial satellite in space was called sputnik.",
				"The largest black hole known to man is the Quasar OJ287, and has an expected mass of 18 billion times that of our own sun.",
				"Pluto is smaller than the Earth’s moon!",
				"Pluto is named after the Roman god of the underworld, not the Disney Dog.",
				"The Sun is the largest object in our solar system.",
				"When fully constructed, the Space Station will be visible for more than 90% of the Earth’s population.",
				"Although Saturn is the second largest planet in our solar system, it is also the lightest planet!",
				"Asteroids are the byproducts of formations in the solar system, more than 4 billion years ago.",
				"Astronauts cannot burp in space!",
				"Android was originally conceived as a camera operating system.",
				"31% of rock star deaths are related to drugs or alcohol.",
				"Coca-Cola owns every domain variation of ahh.com, from 2 H's up to 62 H's.",
				"Facebook has 95 million users in China despite being blocked.",
				"Anne Frank's sister, Margot, also had a diary. It was never found.",
				"Despite the title, most of the dinosaurs from 'Jurassic Park' lived during the Cretaceous period.",
				"Humans put a man on the Moon before they put wheels on luggage.",
				"You can use Skype to call toll free numbers at no charge in the U.S., UK, Taiwan and France.",
				"British workers waste 18 months of their lives commuting.",
				"Bob Marley was buried with his red Gibson guitar, a Bible open to Psalms 23 and a bud of marijuana.",
				"A group of cockroaches is called an intrusion.",
				"In 1894, Japan offered to buy the Philippines from Spain for 40 million pounds.",
				"The average British worker spends 36 days a year answering work emails.",
				"There are virtually no differences in brain anatomy between people with autism and those without.",
				"Nepal was the first country in Asia to introduce gay marriage. It has also outlawed the death penalty.",
				"Americans spend 30% less on Father's Day gifts than on Mother's Day gifts.",
				"The chances of us eating even one spider in our sleep throughout our lifetime is close to 0%.",
				"40% of Americans think that humans and dinosaurs lived at the same time.",
				"Absolut Vodka used to belong to Sweden's government, until they sold it in 2008 for US$8.3 Billion to Pernod Ricard.",
				"Mars has a flag. It was designed by a NASA engineer.",
				"In Halden, a high-security prison in Norway, every cell has a flatscreen TV, an en-suite shower and fluffy, white towels.",
				"There's a bar in Ireland that opened in the year 900 A.D. and is still operational. It's called 'Sean's Bar'.",
				"You are required to show up to vote in Australia. If you don't, you'll face a fine.",
				"The Pyramids of Giza were more ancient to the ancient Romans, than Ancient Rome is ancient to us.",
				"The first thing ever bought and sold across the Internet was a bag of marijuana around 1971.",
				"The UK and Portugal hold the longest standing alliance in the world that is still in force. It was ratified in 1386.",
				"Cats can't see directly below their noses.",
				
];

